export const ZENITH_ORB_TYPE_CONTROLLER = '__ZENITH_ORB_TYPE_CONTROLLER';

export const ZENITH_CONTROLLER_ROUTE = '__ZENITH_CONTROLLER_ROUTE';
export const ZENITH_CONTROLLER_METADATA = '__ZENITH_CONTROLLER_METADATA';
export const ZENITH_CONTROLLER_ROUTE_ARGS = '__ZENITH_CONTROLLER_ROUTE_ARGS';

export const ZENITH_ORB_TYPE_REQUEST_DECODER = '__ZENITH_ORB_TYPE_REQUEST_DECODER';
export const ZENITH_ORB_TYPE_RESPONSE_ENCODER = '__ZENITH_ORB_TYPE_RESPONSE_ENCODER';
export const ZENITH_ORB_TYPE_EXCEPTION_HANDLER = '__ZENITH_ORB_TYPE_EXCEPTION_HANDLER';

export const ZENITH_MIME_TYPES = '__ZENITH_MIME_TYPES';

export const ZENITH_EXCEPTION_HANDLER_EXCEPTIONS = '__ZENITH_EXCEPTION_HANDLER_EXCEPTIONS';

export const ZENITH_VALIDATED = '__ZENITH_VALIDATED';
export const ZENITH_VALIDATED_SCHEMA = '__ZENITH_VALIDATED_SCHEMA';