export const ZENITH_ORB_CONTROLLER = '__ZENITH_ORB_CONTROLLER';

export const ZENITH_CONTROLLER_ROUTE = '__ZENITH_CONTROLLER_ROUTE';
export const ZENITH_CONTROLLER_PATH = '__ZENITH_CONTROLLER_PATH';
export const ZENITH_CONTROLLER_ROUTE_ARGS = '__ZENITH_CONTROLLER_ROUTE_ARGS';