export const ZENITH_ORB_CONTROLLER = '__ZENITH_ORB_CONTROLLER';

export const ZENITH_CONTROLLER_ROUTE = '__ZENITH_CONTROLLER_ROUTE';
export const ZENITH_CONTROLLER_PATH = '__ZENITH_CONTROLLER_PATH';
export const ZENITH_CONTROLLER_ROUTE_ARGS = '__ZENITH_CONTROLLER_ROUTE_ARGS';

export const ZENITH_REQUEST_DECODER = '__ZENITH_REQUEST_DECODER';
export const ZENITH_RESPONSE_ENCODER = '__ZENITH_RESPONSE_ENCODER';

export const ZENITH_MIME_TYPES = '__ZENITH_MIME_TYPES';