export const ZENITH_WEB_HTTP_SERVER_PORT = 'ZENITH_WEB_HTTP_SERVER_PORT';
export const ZENITH_WEB_GLOBAL_ROUTES_PREFIX = 'ZENITH_WEB_GLOBAL_ROUTES_PREFIX';
export const ZENITH_WEB_GENERATE_OPEN_API_DOCS = 'ZENITH_WEB_GENERATE_OPEN_API_DOCS';

export const ZENITH_WEB_DEFAULT_HTTP_SERVER_PORT = 3000;
export const ZENITH_WEB_DEFAULT_GLOBAL_ROUTES_PREFIX = '/';
export const ZENITH_WEB_DEFAULT_GENERATE_OPEN_API_DOCS = false;

export const ZENITH_WEB_SHUTDOWN_TIMEOUT_MS = 'ZENITH_WEB_SHUTDOWN_TIMEOUT_MS';

export const ZENITH_WEB_DEFAULT_SHUTDOWN_TIMEOUT_MS = 10_000;

export const ZENITH_WEB_CORS_ORIGINS = 'ZENITH_WEB_CORS_ORIGINS';
