export const ZENITH_WEB_HTTP_SERVER_PORT = 'ZENITH_WEB_HTTP_SERVER_PORT';
export const ZENITH_WEB_GLOBAL_ROUTES_PREFIX = 'ZENITH_WEB_GLOBAL_ROUTES_PREFIX';
export const ZENITH_WEB_GENERATE_OPEN_API_DOCS = 'ZENITH_WEB_GENERATE_OPEN_API_DOCS';